version: '3.1'

services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 8080:2368
      - 3306:3306
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080
    volumes:
      - ./content/images:/var/lib/ghost/content/images
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example